#!/bin/bash

. ~/.profile
. ~/.bashrc
cd ~/scoreboard;
xinput map-to-output 6 HDMI-1 &
fuser -k 7005/tcp
chromium-browser --kiosk --window-position=0,0 --user-data-dir=/home/wyf/monitor2 --new-window http://output.jsbin.com/sisesoq &
chromium-browser --kiosk --window-position=800,0 --user-data-dir=/home/wyf/monitor1 --new-window http://output.jsbin.com/sisesoq &
PATH=$PATH:/home/wyf/.config/nvm/versions/node/v20.5.1/bin/
/home/wyf/.config/nvm/versions/node/v20.5.1/bin/vite preview --host --port=4173 &
~/spotifyd --no-daemon &
sleep 20s
chromium-browser --window-position=800,0 --user-data-dir=/home/wyf/monitor1 http://localhost:4173/ &
chromium-browser --window-position=0,0 --user-data-dir=/home/wyf/monitor2 http://localhost:4173/local-remote;